environment:
  NODE_PRE_GYP_GITHUB_TOKEN:
    secure: 49KEcACd0Gviy/ZuyCOdAIyi1nacUMvw5+FpFHJespJeOKvMiSocLC79MXXw24p6
  matrix:
    - nodejs_version: "13"
    - nodejs_version: "12"
    - nodejs_version: "11"
    - nodejs_version: "10"
    - nodejs_version: "9"
    - nodejs_version: "8"

platform:
  - x64
  - x86

os: Visual Studio 2015

build_script:
  - npm install

test_script:
  - node --version
  - npm --version
  - npm test

deploy_script:
  - ps: |
      if ($env:APPVEYOR_REPO_COMMIT_MESSAGE.ToLower().Contains('[publish binary]'))
      {
        npm run node-pre-gyp-package
        npm run node-pre-gyp-github-release
      }

artifacts:
  - path: .\build\**\wwindowskill.node

skip_tags: true
version: "0.1.{build}"
