name : Prebuild

on :
  push :
    branches : [ master ]

jobs :
  release :
    if : "startsWith( github.event.head_commit.message, 'version' )"
    runs-on : ${{ matrix.os }}
    strategy :
      fail-fast : false
      matrix :
        os : [ windows-latest ]
        node-version : [ 8.x, 9.x, 10.x, 11.x, 12.x, 13.x, 14.x ]
    steps :
    - uses : actions/checkout@v2
    - name : ${{ matrix.node-version }}
      uses : actions/setup-node@v1
      with :
        node-version : ${{ matrix.node-version }}
    - run : npm install -g npm@latest
    - run : npm i --ignore-scripts
    - run : npm run node-pre-gyp-build
    - run : npm test
    - run : npm run node-pre-gyp-package && npm run node-pre-gyp-github-release
      env :
        NODE_PRE_GYP_GITHUB_TOKEN : ${{ secrets.NODE_PRE_GYP_GITHUB_TOKEN }}
